class LoginModel {
  int? email;
  int? password;
  String? token;

  LoginModel({this.email, this.password});

  // Autogenerated.fromJson(Map<String, dynamic> json) {
  //   userId = json['userId'];
  //   id = json['id'];
  //   title = json['title'];
  //   completed = json['completed'];
  // }

  // Map<String, dynamic> toJson() {
  //   final Map<String, dynamic> data = new Map<String, dynamic>();
  //   data['userId'] = this.userId;
  //   data['id'] = this.id;
  //   data['title'] = this.title;
  //   data['completed'] = this.completed;
  //   return data;
  // }
}
